[package]
name = "github_context"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/github_context.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.3.0"
serde = "1.0.218"
serde_json = "1.0.139"
