id = "gh"
name = "Github context"
description = "Adds context from github"
version = "0.1.0"
schema_version = 1
authors = ["Bjørn Gilstad <github_context_zed@gilstad.io>"]
repository = ""

[[capabilities]]
kind = "process:exec"
command = "git"
args = ["**"]

[slash_commands.pr-link]
description = "Takes a pull request link (github) and adds to context"
requires_argument = true

[slash_commands.pr-open]
description = "List open pull requests in current repository and adds to context"
requires_argument = true
